language: go
go:
  - 1.13
  - master

jobs:
  fast_finish: true

before_install:
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover

install:
  - make deps

script:
  - make lint
  - make test

after_success:
    - $HOME/gopath/bin/goveralls -package=./gyazo -service=travis-ci

notifications:
  email: false
