sudo: false
language: go

go:
  - 1.5

before_install:
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - if ! go get github.com/golang/tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi

script:
  - go test -v ./gyazo -coverprofile=coverage.out
  - $HOME/gopath/bin/gocov convert coverage.out > gocov.json
  - $HOME/gopath/bin/goveralls -gocovdata gocov.json -service=travis-ci
  - make test
