sudo: false
language: go

go:
  - 1.6

before_install:
  - go get github.com/mattn/goveralls
  - go get github.com/golang/tools/cmd/cover

script:
  - make test
  - $HOME/gopath/bin/goveralls -service=travis-ci

notifications:
  email: false
