language: go
sudo: false

before_install:
  - go get github.com/golang/dep/cmd/dep
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover

matrix:
  fast_finish: true
  include:
    - go: 1.7
      script: make test
    - go: 1.8
      script: make test

after_success:
    - $HOME/gopath/bin/goveralls -package=./gyazo -service=travis-ci

notifications:
  email: false
