sudo: false
language: go

go:
  - 1.6

before_install:
  - sudo add-apt-repository ppa:masterminds/glide && sudo apt-get update
  - sudo apt-get install glide
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover

script:
  - make test
  - $HOME/gopath/bin/goveralls -package=./gyazo -service=travis-ci

notifications:
  email: false
