language: go
go:
  - 1.13

before_install:
  - go get -u golang.org/x/lint/golint
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls

install:
  - make deps

script:
  - make lint
  - make test

after_success:
    - $HOME/gopath/bin/goveralls -package=./gyazo -service=travis-ci

notifications:
  email: false
